server:
  port: 8088
  servlet:
    context-path: /

dispatcher:
  interServices:
    - serviceName: service_001
      serviceHostUrl: http://127.0.0.1:8080

    - serviceName: flask
      serviceHostUrl: http://127.0.0.1:51000