server:
  port: 8088
  servlet:
    context-path: /test

route:
  manager:
    routingRules:
      - serviceName: service_001
        serviceUrl: http://127.0.0.1:8080

      - serviceName: service_002
        serviceUrl: http://127.0.0.1:8081