server:
  port: 8088
  servlet:
    context-path: /test

route:
  routes:
    routeList:
      - name: service_001
        url: http://127.0.0.1:8080
        port: 123456

      - name: service_002
        url: http://127.0.0.1:8081
        port: 147258