server:
  port: 8088
  servlet:
    context-path: /test

route:
  routes:
    routingRules:
      - name: service_001
        serviceUrl: http://127.0.0.1:8080

      - name: service_002
        serviceUrl: http://127.0.0.1:8081